### ISSUE TITLE
如何将iView样式引入项目？

### ISSUE THREAD

**Issue by yzqiang** [zangse/vue-chrome-extensions-demo#2]
在给该项目加入iView这样的第三方CSS库的时候，无论如何也加入不进去。
我后来通过修改webpack.config.js文件，成功地将import进来的CSS库编译到dist/static/css目录下面。但是，编译后的CSS文件并没有被引入进来。
我该如何修改才可以经import的iView的CSS文件引入项目呢？

**Comment by zangse** [comment]
我目前的做法是在app.vue里用
`require('../assets/style/reset.scss')`
这种方式实现的
@yzqiang
